bombay_software/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import *
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    # path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('register/', Register, name="register"),
    path('', MyLoginView.as_view(), name='login'),
    path('logout/', Logout, name='logout'),
    path('user/',UserListing,name='user'),
    path('update-password/',Update_password_show,name='update_password_show'),
    path('update-password/save/',Update_password_validation,name="update_password_validation"),
    path('update-password/save/update/',Update_password_save,name='update_password_save'),
    path('profile-edit/',EditProfile,name='profile_edit'),
    # path('user/',UserListing,name='user'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT})]
handler404 = 'authentication.views.handler404'
handler500 = 'authentication.views.handler500'

authentication/forms.py
from django import forms
import phonenumbers
from .models import *
import re, uuid
CHOICES=[('Male','Male'),
         ('Female','Female'),
         ('Others','Others')
         ]
class RegisterUserForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    dob = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    mobile = forms.IntegerField()
    # description_es = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'dob', 'gender', 'email', 'password', 'confirm_password','mobile',
                  'user_type']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Enter a first name.",
            'type': "text"
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Enter a last name.",
            'type': "text"
        })
        self.fields['dob'].widget.attrs.update({
            'class': 'form-control',
            'type': "date",
            'placeholder': "mm/dd/yy"
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Email",
            'type': "email"
        })
        self.fields['mobile'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "number",
            'type': "number"
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Password",
            'type': "password"
        })
        self.fields['confirm_password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Confirm Password",
            'type': 'password'
        })
        self.fields['user_type'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Enter frame length in cm",
            'min':'1'
        })

    def clean(self):    
        super(RegisterUserForm, self).clean()
        if  not User.objects.filter(id=self.instance.pk).exists():
            password = self.cleaned_data.get("password")
            confirm_password = self.cleaned_data.get("confirm_password")
            if len(self.cleaned_data.get("password"))<8:
                self._errors['password'] = self.error_class(['Password should contains minimum 8 characters.'])
                return self.cleaned_data
            if password != confirm_password:
                self._errors['confirm_password'] = self.error_class(['password and confirm_password does not match.'])
                return self.cleaned_data
        else:
            del self._errors['password']
            del self._errors['confirm_password']
            del self._errors['user_type']
        strmobileNumber = '+91' + str(self.cleaned_data.get('mobile'))
        try:
            my_number = phonenumbers.parse(strmobileNumber)
            if not phonenumbers.is_valid_number(my_number):
                self._errors['mobile'] = self.error_class(['Please enter a valid mobile number.'])
                return self.cleaned_data
        except:
            self._errors['mobile'] = self.error_class(['Please enter a valid mobile number.'])
            return self.cleaned_data
        return self.cleaned_data

templates/404-not-found.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>404 Not Found</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <link href="https://site-assets.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">

    <link href="/static/style.css" rel="stylesheet">

</head>

<body>
    <div class="main-wrapper">
        <div class="landing-page bg-image">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="not-found">
                            <div class="image-wrapper">
                                <img src="/static/dist/img/not-found.png" class="w-100">
                            </div>

                            <div class="button-wrapper">
                                <a onclick="window.history.go(-1); return false;" class="btn btn-primary">Go Back</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <style>
    </style>
</body>

</html>

templates/500-not-found.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>500 Internal Server Error</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <link href="https://site-assets.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">

    <link href="/static/style.css" rel="stylesheet">

</head>

<body>
    <div class="main-wrapper">
        <div class="landing-page bg-image">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="not-found">
                            <div class="image-wrapper">
                                <img src="/static/dist/img/500 Internal Server Error-rafiki New.png">
                            </div>

                            <div class="button-wrapper">
                                <a onclick="window.history.go(-1); return false;" class="btn btn-primary">Go Back</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <style>
    </style>
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Task{% endblock %}</title>
  <link rel="icon" type="image/x-icon" href="/static/github-alt.svg">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
  <link rel="stylesheet" href="/static/style.css">
</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img src="/static/github-alt.svg" alt="AdminLTELogo" height="60" width="60">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="#" class="brand-link">

        <img src="/static/github-alt.svg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
          style="opacity: .8">
        <span class="brand-text font-weight-light">Task</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            {% if request.user.gender == 'Male' %}
            <img src="/static/dist/img/avatar5.png" class="img-circle elevation-2" alt="User Image">
            {% else %}
            <img src="/static/dist/img/avatar2.png" class="img-circle elevation-2" alt="User Image">
            {% endif %}
          </div>
          <div class="info">
            <a href="#" class="d-block">{{user.first_name}} {{user.last_name}}</a>
          </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{% url 'user' %}" class="nav-link">
                <i class="fas fa-duotone fa-users"></i>
                <p>
                  User
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="/profile-edit/" class="nav-link">
                <i class="fas fa-edit"></i>
                <p>
                  Edit Profile
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'update_password_show' %}" class="nav-link">
                <i class="fas fa-lock"></i>
                <p>Update Password</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="/logout" onclick="logout(event)" class="nav-link">
                <i class="fas fa-reply"></i>&nbsp;
                <p>
                  Logout
                </p>
              </a>
            </li>
          </ul>
        </nav>



        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    {% block header_content %}
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <!-- <li class="breadcrumb-item"><a href="#"></a></li> -->
                <li class="breadcrumb-item active">Dashboard</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      {% endblock %}
      <!-- /.content-header -->

      {% block content %}
      <!-- Main content -->
      {% endblock %}
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="card">
          <div class="card-body text-center modals">
            <img src="/static/sp.png" class="img-fluid d-block mx-auto w-25 mb-1">
            <i class="fas fa-quote-left fa-2x mb-3 text-danger"></i>
            <h3>Welcome to Python BaseCode Admin panel</h3>
            <p class="text-muted mt-3"><strong class="pr-2">NOTE:</strong>you are successfully loged in</p>
          </div>
        </div>
      </div>
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
      <div class="p-3">
        <h5>Title</h5>
        <p>Sidebar content</p>
      </div>
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->

      <!-- Default to the left -->
      <strong>Copyright &copy; 2022-2023 <a href="#">Python taslk</a>.</strong> All rights reserved.
    </footer>
  </div>
  <!-- ./wrapper -->
  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="/static/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/dist/js/adminlte.min.js"></script>
  <!-- DataTables  & Plugins -->
  <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <script src="/static/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
  <script src="/static/plugins/jszip/jszip.min.js"></script>
  <script src="/static/plugins/pdfmake/pdfmake.min.js"></script>
  <script src="/static/plugins/pdfmake/vfs_fonts.js"></script>
  <script src="/static/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/plugins/datatables-buttons/js/buttons.print.min.js"></script>
  <script src="/static/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
  <script src="/static/plugins/jquery-ui/jquery-ui.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="/static/custom_script.js"></script>
  {% block scriptblock %}
  {% endblock %}
</body>

</html>

templates/change_password.html
<!doctype html>
<html lang="en">

<head>
    <title>Update Password</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/x-icon" href="/static/github-alt.svg">
    <link rel="stylesheet" href="/static/style.css">

</head>

<body>
    <div class="w-100 messages" role="alert">
        <span aria-hidden="true" class="closebtn">×</span>
        <span class="child-message"><strong>Warning!</strong> <span>Password cannot be blank</span></span>
    </div>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-lock"></span>
                        </div>
                        <h3 class="text-center mb-4">Update Password</h3>
                        <form method="POST" onsubmit="javascript: validateForm(event); return false;"name="myform" action='{% url "update_password_save" %}'>
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="password" name="current_password" class="form-control "
                                        id="js-current-password" placeholder="Current Password"
                                        autocomplete="current-password">
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" name="new_password" class="form-control "
                                id="js-new-password" placeholder="New Password" autocomplete="new-password">
                            </div>
                            <div class="form-group">
                                <input type="password" name="new_password_confirmation" class="form-control"
                                        id="js-confirm-new-password" placeholder="Confirm New Password"
                                        autocomplete="new-password">
                            </div>
                            <div class="form-group">
                                <button type="submit"
                                    class="form-control btn btn-primary rounded submit px-3">Confirm New Passsword</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'user' %}">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="/static/custom_script.js"></script>
    
    <script>
        function validateForm(e) {
            e.preventDefault();
            var $form = $(this);
            $.ajax({
                url: '{% url "update_password_validation" %}',
                data: {
                    'Email': $('#js-email').val(),
                    'Current_Password':$('#js-current-password').val(),
                    'New_Passsword': $('#js-new-password').val(),
                    'Confirm_New_Passsword': $('#js-confirm-new-password').val(),
                },
        
                success: function (data) {
                    if (data['response'] == '4') {
                        validation('Password should contains minimum 8 characters.', 'warning')
                    }
                    else if (data['response'] == '2') {
                        validation('please make sure password will be same.', 'warning')
                    }
                    else if (data['response'] == '1') {
                        validation('These credentials do not match our records.', 'warning')
                    }
                    else if (data['response'] == '3') {
                        validation('fields can not be null.', 'warning')
                    }
                    else {
                        ajaxComplete();
                    }
                }
            });
        }
        function ajaxComplete() {
            document.myform.submit();
        
        }
        {% if form.errors %}
        {% for field, errors in form.errors.items %}
        {% for error in errors %}
        validation(`{{error}}`, "warning")
        {% endfor %}
        {% endfor %}
        {% endif %}
        $('#id_username').addClass('form-control', 'rounded-left')
        $('#id_password').addClass('form-control', 'rounded-left')
    </script>
</body>

</html>

templates/profile-edit.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}
{% block header_content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Edit Profile</h1>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block content %}
    <section class="content">
        <div class="container-fluid">
            <form method="POST" enctype="multipart/form-data" action=''>
                {% csrf_token %}
                <div class="card card-primary">
                    <div class="card-header">
                        <h3></h3>
                    </div>
                    <form>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="categories_name">First Name</label>
                                {{form.first_name}}
                                <small>
                                    {{ form.first_name.errors }}
                                </small>
                            </div>
                            <div class="form-group">
                                <label for="categories_name">Last Name </label>
                                {{form.last_name}}
                                <small>
                                    {{ form.last_name.errors }}
                                </small>
                            </div>
                            <div class="form-group">
                                <label for="categories_name">DOB </label>
                                {{form.dob}}
                                <small>
                                    {{ form.dob.errors }}
                                </small>
                            </div>
                            <div class="form-group">
                                <label for="categories_name">Gender</label>
                                {{form.gender}}
                                <small>
                                    {{ form.gender.errors }}
                                </small>
                            </div>
                            <div class="form-group">
                                <label for="categories_name">Email </label>
                                {{form.email}}
                                <small>
                                    {{ form.email.errors }}
                                </small>
                            </div>
                            <div class="form-group">
                                <label for="categories_name">Mobile </label>
                                {{form.mobile}}
                                <small>
                                    {{ form.mobile.errors }}
                                </small>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </form> <!-- </div>
    </div> -->

        </div>
    </section>
    {% endblock %}

    {% block scriptblock %}
<script>
    flatpickr('#id_dob', { dateFormat: 'm/d/Y' });
    $(function () {
        var url = window.location;
        // for single sidebar menu
        $('ul.nav-sidebar a').filter(function () {
            return this.href == url;
        }).addClass('active');

        // for sidebar menu and treeview
        $('ul.nav-treeview a').filter(function () {
            return this.href == url;
        }).parentsUntil(".nav-sidebar > .nav-treeview")
            .css({ 'display': 'block' })
            .addClass('menu-open').prev('a')
            .addClass('active');
    });

    $('#id_gender').addClass('row col-12 col-sm-6 col-xs-12')
    $('#id_gender').css('justify-content', 'flex-start')
    $('#id_gender').children().css('margin-right', '17px')
</script>
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block header_content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">User</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    {% endblock %}
    {% block content %}
    {% for message in messages|slice:":1" %}
    <div class="alert {{ message.tags }} django messages" role="alert">
        <span aria-hidden="true" class="closebtn">&times;</span>
        <span class="django-child-message">{{ message }}</span>
    </div>
    {% endfor %}
    <div class="w-100 messages" role="alert">
        <span aria-hidden="true" class="closebtn">×</span>
        <span class="child-message"><strong>Warning!</strong> <span>Password cannot be blank</span></span>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Users</h3>
                        </div>
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Mobile</th>
                                        <th>Dob</th>
                                        <th>Gender</th>
                                        <th>Type</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for value in data %}
                                    <tr>
                                        <td style="text-transform: capitalize;">
                                            {{ value.first_name }} {{value.last_name }}
                                        </td>
                                        <td>{{ value.email }}</td>
                                        <td>{{ value.mobile }}</td>
                                        <td>{{ value.dob }}</td>
                                        <td>{{ value.gender}}</td>
                                        <td>{{ value.user_type}}</td>
                                    </tr>
                                    {% endfor %}
                                    </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<!-- Page specific script -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $('.card-body').append(`<div class="custom-pagination" style="position:relative; top:13px;"><ul class="pagination" style="justify-content: right;"></ul></div>`)
    pagination_data = JSON.parse(`{{pagination_data|safe}}`)
    if(pagination_data[0]['page_obj_has_previous']){
        $('.pagination').append(`<li class="paginate_button page-item previous" id="example1_previous"><a href="?page=${pagination_data[0]['previous_page_number']}" aria-controls="example1" data-dt-idx="${pagination_data[0]['previous_page_number']}" tabindex="0" class="page-link">Previous</a></li>`)
    }else{
        $('.pagination').append(`<li class="paginate_button page-item previous disabled" id="example1_previous"><a href="#" aria-controls="example1" data-dt-idx="" tabindex="0" class="page-link">Previous</a></li>`)
    }
    $.each(pagination_data[0]['page_list'], function (value) {
        value = value+1
        console.log(pagination_data[0]['page_obj_number'], value)
        if(pagination_data[0]['page_obj_number'] == value){
            $('.pagination').append(`<li class="paginate_button page-item active"><a href="?page=${value}" aria-controls="example1" data-dt-idx="${value}" tabindex="0" class="page-link">${value}</a></li>`)
        }else if(value!=0){
            $('.pagination').append(`<li class="paginate_button page-item"><a href="?page=${value}" aria-controls="example1" data-dt-idx="${value}" tabindex="0" class="page-link">${value}</a></li>`)
        }
    })
    if(pagination_data[0]['page_obj_has_next']){
        $('.pagination').append(`<li class="paginate_button page-item next" id="example1_next"><a href="?page=${pagination_data[0]['page_obj_next_page_number']}" aria-controls="example1" data-dt-idx="${pagination_data[0]['page_obj_next_page_number']}" tabindex="0" class="page-link">Next</a></li>`)
    }else{
        $('.pagination').append(`<li class="paginate_button page-item next disabled" id="example1_next"><a href="#" aria-controls="example1" data-dt-idx="" tabindex="0" class="page-link">Next</a></li>`)
    }
</script>
</body>

</html>
{% endblock %}